development:
  adapter: postgresql
  encoding: unicode
  database: mstwjs_development
  pool: 5
  host: localhost

test: &test
  username: postgres
  adapter: postgresql
  encoding: unicode
  database: mstwjs_test
  pool: 5
  host: localhost
